BEGIN TRANSACTION;
INSERT INTO schema_migrations VALUES('20161026163427');
-- DO NOT CHANGE ABOVE THIS LINE
-- Place Migration statements below


CREATE TABLE TestOrders (
	id INTEGER NOT NULL AUTO_INCREMENT,
	Date TIMESTAMP NOT NULL,
	testPerson_id INTEGER,
	PRIMARY KEY (id),
	FOREIGN KEY (testPerson_id)
		REFERENCES TestPeople (id)
		ON DELETE CASCADE
);

-- DO NOT CHANGE BELOW THIS LINE
COMMIT;
